"""Partial release reconciliation with real remote refs and isolated publication."""

from __future__ import annotations

import contextlib
import json
import os
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

sys.path.insert(0, str(Path(__file__).parents[1] / "scripts"))
import release_publish as publication


class PublicationTests(unittest.TestCase):
    def setUp(self) -> None:
        self.temporary = tempfile.TemporaryDirectory()
        self.addCleanup(self.temporary.cleanup)
        self.root = Path(self.temporary.name)
        self.remote, self.checkout = self.root / "remote.git", self.root / "checkout"
        subprocess.run(
            ["git", "init", "--bare", str(self.remote)], check=True, capture_output=True
        )
        subprocess.run(
            ["git", "init", "-b", "main", str(self.checkout)],
            check=True,
            capture_output=True,
        )
        self.previous = Path.cwd()
        os.chdir(self.checkout)
        self.addCleanup(os.chdir, self.previous)
        self.git("config", "user.name", "Test")
        self.git("config", "user.email", "test@example.com")
        self.git("remote", "add", "origin", str(self.remote))
        self.message = "chore(release): {version}\n\nAutomatically generated by python-semantic-release"
        self.config = self.root / "config.json"
        self.config.write_text(
            json.dumps(
                {
                    "semantic_release": {
                        "commit_message": self.message,
                        "version_toml": ["pyproject.toml:project.version"],
                    }
                }
            )
        )
        self.metadata("0.18.1")
        Path("app.py").write_text("print('validated application')\n")
        Path("uv.lock").write_text("locked\n")
        self.git("add", ".")
        self.git("commit", "-m", "chore: base")
        self.git("tag", "v0.18.1")
        self.git("commit", "--allow-empty", "-m", "feat: application")
        self.application = self.git("rev-parse", "HEAD")
        self.git("push", "origin", "main", "--tags")
        self.published = None
        self.calls = []
        self.failure = ""
        self.notes_failures = 0
        self.stack = contextlib.ExitStack()
        self.addCleanup(self.stack.close)
        self.stack.enter_context(patch.object(publication, "semantic", self.semantic))
        self.stack.enter_context(patch.object(publication, "release", self.release))
        self.stack.enter_context(
            patch.object(publication, "predicted_at_parent", return_value="v0.19.0")
        )
        self.stack.enter_context(patch.object(publication.time, "sleep"))

    def git(self, *args: str) -> str:
        return publication.git(*args)

    def metadata(self, version: str) -> None:
        Path("pyproject.toml").write_text(
            f'[project]\nname = "fixture"\nversion = "{version}"\n'
        )

    def release(self, tag: str) -> dict | None:
        self.assertEqual(tag, "v0.19.0")
        return self.published

    def semantic(self, config: Path, *args: str, cwd: Path | None = None) -> str:
        self.calls.append(args)
        if "--print-tag" in args:
            return "v0.19.0"
        if args[0] == "changelog":
            if self.notes_failures:
                self.notes_failures -= 1
                raise subprocess.CalledProcessError(
                    1, "semantic-release", "503 Server Error"
                )
            self.published = {"id": 1, "tag_name": "v0.19.0"}
            return ""
        if "--no-push" in args:
            self.metadata("0.19.0")
            return ""
        if "--no-commit" not in args:
            self.metadata("0.19.0")
            self.git("add", "pyproject.toml")
            self.git("commit", "-m", self.message.format(version="0.19.0"))
            self.git("push", "origin", "main")
        if self.failure == "version_push":
            raise subprocess.CalledProcessError(
                1, "semantic-release", "remote rejected (failed)"
            )
        self.git("tag", "-a", "v0.19.0", "-m", "v0.19.0")
        self.git("push", "origin", "refs/tags/v0.19.0")
        if self.failure == "tag_push":
            raise subprocess.CalledProcessError(
                1, "semantic-release", "release creation failed"
            )
        self.published = {"id": 1, "tag_name": "v0.19.0"}
        return ""

    def version_commit(self) -> str:
        self.metadata("0.19.0")
        self.git("add", "pyproject.toml")
        self.git("commit", "-m", self.message.format(version="0.19.0"))
        self.git("push", "origin", "main")
        return self.git("rev-parse", "HEAD")

    def run_publish(self, expected: str = "") -> tuple[bool, str]:
        return publication.publish(self.config, "refs/heads/main", False, expected)

    def test_failure_after_version_push_recovers_without_another_commit(self) -> None:
        self.failure = "version_push"
        original = subprocess.run
        with patch.object(publication.subprocess, "run", wraps=subprocess.run) as run:
            # uv lock is consumer preparation, simulated separately from real Git.
            run.side_effect = lambda cmd, **kw: (
                subprocess.CompletedProcess(cmd, 0)
                if cmd[:2] == ["uv", "lock"]
                else original(cmd, **kw)
            )
            with self.assertRaises(subprocess.CalledProcessError):
                self.run_publish()
        revision = self.git("rev-parse", "HEAD")
        self.assertNotEqual(revision, self.application)
        self.assertIsNone(publication.remote_tag("v0.19.0"))
        self.failure = ""
        self.assertEqual(self.run_publish("v0.19.0"), (True, "v0.19.0"))
        self.assertEqual(self.git("rev-parse", "HEAD"), revision)
        self.assertEqual(publication.remote_tag("v0.19.0"), revision)
        self.assertIn(
            (
                "version",
                "--no-commit",
                "--no-changelog",
                "--skip-build",
                "--vcs-release",
            ),
            self.calls,
        )

    def test_failure_after_tag_push_recovers_using_release_notes_only(self) -> None:
        revision = self.version_commit()
        self.failure = "tag_push"
        with self.assertRaises(subprocess.CalledProcessError):
            self.run_publish()
        self.assertEqual(publication.remote_tag("v0.19.0"), revision)
        self.assertIsNone(self.published)
        self.failure = ""
        self.calls.clear()
        self.assertEqual(self.run_publish(), (True, "v0.19.0"))
        self.assertEqual(
            self.calls, [("changelog", "--post-to-release-tag", "v0.19.0")]
        )

    def test_existing_tag_missing_release_and_repeated_recovery(self) -> None:
        revision = self.version_commit()
        self.git("tag", "v0.19.0")
        self.git("push", "origin", "refs/tags/v0.19.0")
        self.assertEqual(self.run_publish(), (True, "v0.19.0"))
        self.calls.clear()
        self.assertEqual(self.run_publish(), (True, "v0.19.0"))
        self.assertEqual(self.calls, [])
        self.assertEqual(self.git("rev-parse", "HEAD"), revision)

    def test_already_published_ancestor_can_be_verified_after_consumer_fix(
        self,
    ) -> None:
        revision = self.version_commit()
        self.git("tag", "v0.19.0")
        self.git("push", "origin", "refs/tags/v0.19.0")
        self.published = {"id": 1, "tag_name": "v0.19.0"}
        Path("app.py").write_text("new validated consumer\n")
        self.git("commit", "-am", "docs: consumer fix")
        self.git("push", "origin", "main")
        self.assertEqual(self.run_publish("v0.19.0"), (True, "v0.19.0"))
        self.assertEqual(self.calls, [])
        self.assertEqual(publication.remote_tag("v0.19.0"), revision)

    def test_missing_ancestor_release_is_not_published_on_newer_application(
        self,
    ) -> None:
        self.version_commit()
        self.git("tag", "v0.19.0")
        self.git("push", "origin", "refs/tags/v0.19.0")
        Path("app.py").write_text("new validated consumer\n")
        self.git("commit", "-am", "feat: newer application")
        self.git("push", "origin", "main")
        with self.assertRaisesRegex(ValueError, "no matching"):
            self.run_publish("v0.19.0")
        self.assertFalse(any(call[0] == "changelog" for call in self.calls))

    def test_real_psr_recovery_creates_same_tag_without_new_version_commit(
        self,
    ) -> None:
        revision = self.version_commit()
        # Use PSR itself to verify the supported recovery flags and parent-derived
        # intent. Remote mutation is disabled in this integration test.
        self.git(
            "remote", "set-url", "origin", "https://github.com/example/fixture.git"
        )
        config = json.loads(self.config.read_text())
        config["semantic_release"].update(
            {"allow_zero_version": True, "major_on_zero": False}
        )
        self.config.write_text(json.dumps(config))

        def psr(cwd: Path, *args: str) -> str:
            return subprocess.check_output(
                [
                    sys.executable,
                    "-m",
                    "semantic_release",
                    "--config",
                    str(self.config),
                    *args,
                ],
                cwd=cwd,
                text=True,
            ).strip()

        with tempfile.TemporaryDirectory() as temporary:
            parent = Path(temporary) / "parent"
            subprocess.run(
                [
                    "git",
                    "clone",
                    "--quiet",
                    "--shared",
                    str(self.checkout),
                    str(parent),
                ],
                check=True,
            )
            publication.git("checkout", "-B", "main", self.application, cwd=parent)
            self.assertEqual(psr(parent, "version", "--print-tag"), "v0.19.0")
        self.assertEqual(psr(self.checkout, "version", "--print-tag"), "v0.19.0")
        psr(
            self.checkout,
            "version",
            "--no-commit",
            "--no-changelog",
            "--skip-build",
            "--no-push",
            "--no-vcs-release",
        )
        self.assertEqual(self.git("rev-parse", "refs/tags/v0.19.0^{commit}"), revision)
        self.assertEqual(self.git("rev-parse", "HEAD"), revision)

    def test_real_psr_can_create_missing_release_for_existing_tag(self) -> None:
        from click.testing import CliRunner
        from semantic_release.cli.commands.main import main
        from semantic_release.hvcs.github import Github

        self.version_commit()
        self.git("tag", "v0.19.0")
        self.git(
            "remote", "set-url", "origin", "https://github.com/example/fixture.git"
        )
        with patch.object(Github, "create_or_update_release", return_value=1) as create:
            result = CliRunner().invoke(
                main,
                [
                    "--config",
                    str(self.config),
                    "changelog",
                    "--post-to-release-tag",
                    "v0.19.0",
                ],
            )
        self.assertEqual(result.exit_code, 0, result.output)
        self.assertEqual(create.call_args.args[0], "v0.19.0")
        self.assertIn("Application", create.call_args.args[1])

    def test_conflicting_remote_tag_fails_before_mutation(self) -> None:
        self.version_commit()
        self.git("tag", "v0.19.0", self.application)
        self.git("push", "origin", "refs/tags/v0.19.0")
        with self.assertRaisesRegex(ValueError, "Conflicting"):
            self.run_publish()
        self.assertEqual(self.calls, [])
        self.published = {"id": 1, "tag_name": "v0.19.0"}
        with self.assertRaisesRegex(ValueError, "Conflicting"):
            self.run_publish("v0.19.0")

    def test_published_ancestor_conflict_is_not_accepted_as_recovery(self) -> None:
        self.version_commit()
        self.git("tag", "v0.19.0", self.application)
        self.git("push", "origin", "refs/tags/v0.19.0")
        self.published = {"id": 1, "tag_name": "v0.19.0"}
        Path("app.py").write_text("new validated consumer\n")
        self.git("commit", "-am", "docs: caller")
        self.git("push", "origin", "main")
        with self.assertRaisesRegex(ValueError, "no matching intended"):
            self.run_publish("v0.19.0")
        self.assertEqual(self.calls, [])

    def test_superseded_application_revision_is_never_published(self) -> None:
        self.version_commit()
        self.git("checkout", "--detach", self.application)
        with self.assertRaisesRegex(ValueError, "superseded"):
            self.run_publish()
        self.assertEqual(self.calls, [])

    def test_superseded_version_revision_is_never_published(self) -> None:
        version = self.version_commit()
        Path("app.py").write_text("new unvalidated code\n")
        self.git("commit", "-am", "feat: newer application")
        self.git("push", "origin", "main")
        self.git("checkout", "--detach", version)
        with self.assertRaisesRegex(ValueError, "superseded"):
            self.run_publish()

    def test_metadata_and_parent_prediction_must_agree(self) -> None:
        self.version_commit()
        with patch.object(publication, "predicted_at_parent", return_value="v0.20.0"):
            with self.assertRaisesRegex(ValueError, "intent"):
                self.run_publish()
        with self.assertRaisesRegex(ValueError, "Requested"):
            self.run_publish("v0.20.0")
        self.assertEqual(self.calls, [])

    def test_disguised_application_change_is_not_a_version_commit(self) -> None:
        self.metadata("0.19.0")
        Path("app.py").write_text("different application\n")
        self.git("commit", "-am", self.message.format(version="0.19.0"))
        self.git("push", "origin", "main")
        with self.assertRaisesRegex(ValueError, "outside declared"):
            self.run_publish()

    def test_transient_release_failure_is_bounded_and_rechecks_state(self) -> None:
        self.version_commit()
        self.git("tag", "v0.19.0")
        self.git("push", "origin", "refs/tags/v0.19.0")
        self.notes_failures = 2
        self.assertEqual(self.run_publish(), (True, "v0.19.0"))
        self.assertEqual(len(self.calls), 3)

    def test_transient_retry_exhaustion_fails_after_three_attempts(self) -> None:
        self.version_commit()
        self.git("tag", "v0.19.0")
        self.git("push", "origin", "refs/tags/v0.19.0")
        self.notes_failures = 4
        with self.assertRaises(subprocess.CalledProcessError):
            self.run_publish()
        self.assertEqual(len(self.calls), 3)
        self.assertIsNone(self.published)

    def test_lost_release_response_is_reconciled_without_duplicate_publication(
        self,
    ) -> None:
        self.version_commit()
        self.git("tag", "v0.19.0")
        self.git("push", "origin", "refs/tags/v0.19.0")

        def publish_then_lose_response(*args, **kwargs):
            self.published = {"id": 1, "tag_name": "v0.19.0"}
            raise subprocess.CalledProcessError(
                1, "semantic-release", "502 Server Error"
            )

        with patch.object(
            publication, "semantic", side_effect=publish_then_lose_response
        ) as command:
            self.assertEqual(self.run_publish(), (True, "v0.19.0"))
        self.assertEqual(command.call_count, 1)

    def test_cli_failure_does_not_report_success_outputs(self) -> None:
        output = self.root / "outputs"
        with (
            patch.dict(
                os.environ,
                {"RELEASE_REF": "refs/heads/main", "GITHUB_OUTPUT": str(output)},
            ),
            patch.object(sys, "argv", ["release_publish", str(self.config)]),
            patch.object(
                publication, "publish", side_effect=ValueError("missing remote release")
            ),
        ):
            self.assertEqual(publication.main(), 1)
        self.assertFalse(output.exists())

    def test_generic_rejection_is_not_retried(self) -> None:
        self.version_commit()
        self.failure = "version_push"
        with self.assertRaises(subprocess.CalledProcessError):
            self.run_publish()
        self.assertEqual(sum("--vcs-release" in call for call in self.calls), 1)

    def test_missing_remote_release_after_success_is_failure(self) -> None:
        self.version_commit()
        with patch.object(publication, "release", return_value=None):
            with self.assertRaisesRegex(ValueError, "missing after"):
                self.run_publish()

    def test_psr_cannot_emit_unverified_actions_outputs(self) -> None:
        with (
            patch.dict(os.environ, {"GITHUB_OUTPUT": "forbidden"}),
            patch.object(publication.subprocess, "run") as run,
        ):
            run.return_value = subprocess.CompletedProcess([], 0, "v0.19.0\n", "")
            self.assertEqual(publication.semantic.__name__, "semantic")
            # Exercise the real command wrapper rather than the fixture publisher.
            PublicationTests.real_semantic(self.config, "version", "--print-tag")
            self.assertNotIn("GITHUB_OUTPUT", run.call_args.kwargs["env"])

    real_semantic = staticmethod(publication.semantic)


if __name__ == "__main__":
    unittest.main()
