"""Reconcile semantic-release publication from an immutable validated checkout.

Recovery requires a new run validating the generated version commit. Old runs
remain superseded. Only Python semantic-release mutates version files/tags/releases.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
import tempfile
import time
import tomllib
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path

from release_head import is_current


SHA = re.compile(r"[0-9a-f]{40}\Z")
VERSION = r"[0-9]+\.[0-9]+\.[0-9]+(?:-[0-9A-Za-z.-]+)?(?:\+[0-9A-Za-z.-]+)?"
TRANSIENT = {429, 502, 503, 504}


def git(*args: str, cwd: Path | None = None) -> str:
    return subprocess.check_output(["git", *args], cwd=cwd, text=True).strip()


def semantic(config: Path, *args: str, cwd: Path | None = None) -> str:
    # PSR emits optimistic Actions outputs before creating the GitHub release.
    # Only this helper's final verified result may reach the caller outputs.
    env = {k: v for k, v in os.environ.items() if k != "GITHUB_OUTPUT"}
    result = subprocess.run(
        ["uv", "run", "--frozen", "semantic-release", "--config", str(config), *args],
        cwd=cwd,
        env=env,
        text=True,
        capture_output=True,
    )
    print(result.stdout, end="")
    print(result.stderr, end="", file=sys.stderr)
    if result.returncode:
        raise subprocess.CalledProcessError(
            result.returncode, "semantic-release", result.stdout + result.stderr
        )
    return result.stdout.strip()


def remote_tag(tag: str) -> str | None:
    subprocess.run(["git", "check-ref-format", f"refs/tags/{tag}"], check=True)
    refs = {}
    for line in git(
        "ls-remote", "origin", f"refs/tags/{tag}", f"refs/tags/{tag}^{{}}"
    ).splitlines():
        sha, ref = line.split("\t")
        if not SHA.fullmatch(sha):
            raise ValueError("Invalid remote tag revision")
        refs[ref] = sha
    if not refs:
        return None
    return refs.get(f"refs/tags/{tag}^{{}}", refs[f"refs/tags/{tag}"])


def release(tag: str) -> dict | None:
    repository = os.environ["GITHUB_REPOSITORY"]
    if not re.fullmatch(r"[\w.-]+/[\w.-]+", repository):
        raise ValueError("Invalid GitHub repository")
    url = f"https://api.github.com/repos/{repository}/releases/tags/{urllib.parse.quote(tag, safe='')}"
    request = urllib.request.Request(
        url,
        headers={
            "Authorization": f"Bearer {os.environ['GITHUB_TOKEN']}",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
        },
    )
    for attempt in range(3):
        try:
            with urllib.request.urlopen(request, timeout=30) as response:
                value = json.load(response)
            if (
                not isinstance(value, dict)
                or value.get("tag_name") != tag
                or not isinstance(value.get("id"), int)
            ):
                raise ValueError("Ambiguous GitHub release response")
            if value.get("draft") is not False or not value.get("published_at"):
                raise ValueError("Release exists but is not published")
            return value
        except urllib.error.HTTPError as error:
            if error.code == 404:
                return None
            if error.code not in TRANSIENT or attempt == 2:
                raise ValueError(
                    f"GitHub release lookup failed: HTTP {error.code}"
                ) from None
            time.sleep(2**attempt)
    raise AssertionError("unreachable")


def require_current(ref: str) -> str:
    if not is_current(ref):
        raise ValueError(
            "Validated checkout was superseded; dispatch a fresh validated run"
        )
    return git("rev-parse", "HEAD")


def predicted_at_parent(config: Path, ref: str, directory: Path, parent: str) -> str:
    # Independent clone: no checkout changes in the validated tree; no publishing
    # credentials or writable remote needed for this print-only calculation.
    with tempfile.TemporaryDirectory(prefix="release-intent-") as temporary:
        clone = Path(temporary) / "repository"
        subprocess.run(
            [
                "git",
                "clone",
                "--quiet",
                "--shared",
                git("rev-parse", "--show-toplevel"),
                str(clone),
            ],
            check=True,
        )
        git("checkout", "-B", ref.removeprefix("refs/heads/"), parent, cwd=clone)
        return semantic(config, "version", "--print-tag", cwd=clone / directory)


def recovery_version(config: dict, message: str) -> str | None:
    template = config.get(
        "commit_message",
        "{version}\n\nAutomatically generated by python-semantic-release",
    )
    if template.count("{version}") != 1:
        raise ValueError(
            "Recovery requires one {version} in the release commit message"
        )
    pattern = re.escape(template.strip()).replace(
        re.escape("{version}"), f"({VERSION})"
    )
    match = re.fullmatch(pattern, message.strip())
    return match.group(1) if match else None


def verify_version_commit(
    config: dict, version: str, parent: str, directory: Path, revision: str = "HEAD"
) -> None:
    parents = git("rev-list", "--parents", "-n", "1", revision).split()
    if len(parents) != 2 or parents[1] != parent:
        raise ValueError("Recovery requires a single-parent version commit")
    allowed = {str(directory / "uv.lock")}
    changelog = config.get("changelog", {})
    allowed.add(
        str(
            directory
            / changelog.get("default_templates", {}).get(
                "changelog_file", "CHANGELOG.md"
            )
        )
    )
    declarations = config.get("version_toml", [])
    if not declarations or config.get("version_variables"):
        raise ValueError("Version-commit recovery requires TOML version declarations")
    for declaration in declarations:
        filename, key = declaration.split(":", 1)
        path = directory / filename
        if path.is_absolute() or ".." in path.parts:
            raise ValueError("Version paths must stay inside the repository")
        allowed.add(str(path))
        value = tomllib.loads(git("show", f"{revision}:{path}"))
        for part in key.split("."):
            value = value[part]
        if value != version:
            raise ValueError("Version commit metadata disagrees with intended version")
    changed = set(git("diff", "--name-only", parent, revision).splitlines())
    if not changed or not changed <= allowed:
        raise ValueError(
            "Version commit contains changes outside declared release metadata"
        )


def verify_published(tag: str, revision: str, ref: str) -> None:
    if require_current(ref) != revision:
        raise ValueError("Release revision changed during publication")
    if remote_tag(tag) != revision:
        raise ValueError(
            "Remote release tag is missing or targets a conflicting revision"
        )
    if release(tag) is None:
        raise ValueError("GitHub release is missing after publication")


def post_missing_release(config: Path, tag: str, revision: str, ref: str) -> None:
    for attempt in range(3):
        require_current(ref)
        if remote_tag(tag) != revision:
            raise ValueError(
                "Conflicting or missing tag before release-note publication"
            )
        if release(tag) is not None:
            return
        try:
            require_current(ref)
            semantic(config, "changelog", "--post-to-release-tag", tag)
            return
        except subprocess.CalledProcessError as error:
            # A generic rejected push, 403, auth failure, or ambiguous failure is
            # never retried. Only explicit HTTP transient failures are eligible.
            if attempt == 2 or not re.search(
                r"\b(?:429|502|503|504) (?:Client|Server) Error\b", error.output or ""
            ):
                raise
            time.sleep(2**attempt)


def publish(
    config_path: Path, ref: str, tag_merged_commit: bool, expected: str = ""
) -> tuple[bool, str]:
    validated = require_current(ref)
    root = Path(git("rev-parse", "--show-toplevel"))
    directory = Path.cwd().relative_to(root)
    config = json.loads(config_path.read_text())["semantic_release"]
    version = (
        recovery_version(config, git("log", "-1", "--format=%B"))
        if not tag_merged_commit
        else None
    )
    if expected and version is None:
        # A repaired consumer may have advanced main since the release completed.
        # Reconcile a fully published ancestor without any publication mutation.
        target = remote_tag(expected)
        if target is not None and release(expected) is not None:
            if git("rev-parse", f"refs/tags/{expected}^{{commit}}") != target:
                raise ValueError("Conflicting local and remote recovery tag")
            subprocess.run(
                ["git", "merge-base", "--is-ancestor", target, validated], check=True
            )
            if not tag_merged_commit:
                tagged_version = recovery_version(
                    config, git("log", "-1", "--format=%B", target)
                )
                if (
                    tagged_version is None
                    or config.get("tag_format", "v{version}").format(
                        version=tagged_version
                    )
                    != expected
                ):
                    raise ValueError(
                        "Published recovery tag has no matching intended version commit"
                    )
                parent = git("rev-parse", f"{target}^")
                verify_version_commit(config, tagged_version, parent, directory, target)
                if predicted_at_parent(config_path, ref, directory, parent) != expected:
                    raise ValueError(
                        "Published recovery tag disagrees with parent-derived intent"
                    )
            require_current(ref)
            if remote_tag(expected) != target or release(expected) is None:
                raise ValueError("Recovery publication changed during verification")
            return True, expected
    if version:
        parent = git("rev-parse", "HEAD^")
        verify_version_commit(config, version, parent, directory)
        tag = config.get("tag_format", "v{version}").format(version=version)
        if predicted_at_parent(config_path, ref, directory, parent) != tag:
            raise ValueError(
                "Version commit disagrees with semantic-release intent at its parent"
            )
        if expected and expected != tag:
            raise ValueError("Requested recovery tag disagrees with intended release")
        target = remote_tag(tag)
        if target is not None and target != validated:
            raise ValueError("Conflicting remote tag target")
        existing = release(tag)
        if existing is not None and target is None:
            raise ValueError("GitHub release exists without its intended remote tag")
        require_current(ref)
        if target is None:
            if config.get("add_partial_tags"):
                raise ValueError(
                    "Recovery cannot force-update semantic-release partial tags"
                )
            if git("tag", "--list", tag):
                raise ValueError(
                    "Unpublished local tag is ambiguous; use a clean fresh run"
                )
            if semantic(config_path, "version", "--print-tag") != tag:
                raise ValueError("Recovery would create another version")
            require_current(ref)
            semantic(
                config_path,
                "version",
                "--no-commit",
                "--no-changelog",
                "--skip-build",
                "--vcs-release",
            )
        elif existing is None:
            post_missing_release(config_path, tag, validated, ref)
        verify_published(tag, validated, ref)
        # Idempotent reconciliation returns the verified tag even on a repeated
        # dispatch, allowing downstream delivery to resume without another version.
        return True, tag

    tag = semantic(config_path, "version", "--print-tag")
    if expected:
        # Dynamic/tag-at-merge releases can recover a missing GitHub release only
        # at the exact validated tag target. No version commit is inferred.
        if not tag_merged_commit or expected != tag or remote_tag(tag) != validated:
            raise ValueError(
                "Requested recovery has no matching validated release commit"
            )
        post_missing_release(config_path, tag, validated, ref)
        verify_published(tag, validated, ref)
        return True, tag
    target = remote_tag(tag)
    if target is not None:
        local_target = git("rev-parse", f"refs/tags/{tag}^{{commit}}")
        if target != local_target:
            raise ValueError("Local and remote tag targets disagree")
        subprocess.run(
            ["git", "merge-base", "--is-ancestor", target, validated], check=True
        )
        if target == validated:
            post_missing_release(config_path, tag, validated, ref)
            verify_published(tag, validated, ref)
            return True, tag
        return False, ""
    if release(tag) is not None:
        raise ValueError("GitHub release exists without the intended tag")
    if not tag_merged_commit:
        semantic(
            config_path,
            "version",
            "--no-commit",
            "--no-tag",
            "--no-push",
            "--no-vcs-release",
            "--skip-build",
        )
        subprocess.run(["uv", "lock"], check=True)
        subprocess.run(["git", "add", "uv.lock"], check=True)
    require_current(ref)
    options = (
        ["--no-commit", "--no-changelog", "--skip-build"] if tag_merged_commit else []
    )
    semantic(config_path, "version", "--vcs-release", *options)
    revision = git("rev-parse", "HEAD")
    if tag_merged_commit:
        if revision != validated:
            raise ValueError("Tag-at-merge release changed the validated revision")
    else:
        generated = recovery_version(config, git("log", "-1", "--format=%B"))
        if (
            generated is None
            or config.get("tag_format", "v{version}").format(version=generated) != tag
        ):
            raise ValueError("Published version disagrees with intended release")
        if git("rev-list", "--parents", "-n", "1", "HEAD").split() != [
            revision,
            validated,
        ]:
            raise ValueError(
                "Generated release is not a direct child of the validated revision"
            )
    verify_published(tag, revision, ref)
    return True, tag


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("config", type=Path)
    parser.add_argument("--tag-merged-commit", action="store_true")
    args = parser.parse_args()
    try:
        released, tag = publish(
            args.config.resolve(),
            os.environ["RELEASE_REF"],
            args.tag_merged_commit,
            os.environ.get("RECOVERY_TAG", ""),
        )
        with Path(os.environ["GITHUB_OUTPUT"]).open("a") as stream:
            stream.write(f"released={str(released).lower()}\nrelease_tag={tag}\n")
    except (ValueError, KeyError, OSError, subprocess.CalledProcessError) as error:
        print(
            f"Release reconciliation failed: {error}. Dispatch a fresh run on the version commit after resolving the failure.",
            file=sys.stderr,
        )
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
